# FinalTest
pi.py is test1
Point.py is test2

Point.py를 수정후 재업로드를 하려고 했으나 
업로드상의 오류가 발생하여 급히 새로 만들고 다시 올렸습니다
